# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled0.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fmm8kpT5yfWKKur5yCK6bzs18pF1796I
"""

import pandas as pd

df = pd.read_csv('Seminar_10/data20152019.csv', sep=';', encoding='cp1251')

df = df.iloc[2:19, :]

df = pd.DataFrame(df, columns= ['Субъект РФ', 'Численность студентов очно-заочная (вечерняя) форма, человек, 2015'])

max_students = df['Численность студентов очно-заочная (вечерняя) форма, человек, 2015'].max()
max_region = df[df['Численность студентов очно-заочная (вечерняя) форма, человек, 2015'] == max_students]['Субъект РФ'].values[0]

print('Область с наибольшей численностью студентов:', max_region)
print('Численность студентов в этой области:', max_students)