# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14silLSrpRR5IiBnAi-_oI4qPFo3onot6
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('Seminar_10/data20152019.csv', sep=';', encoding='cp1251')

df = pd.DataFrame(df, columns= ['Субъект РФ', 'Численность студентов заочная форма, человек, 2019'])

# Фильтрация данных, где количество студентов не превышает 10 000
filtered_data = df[df['Численность студентов заочная форма, человек, 2019'] <= 10000]

# Построение диаграммы
plt.figure(figsize=(12, 6))
sns.barplot(x='Субъект РФ', y='Численность студентов заочная форма, человек, 2019', data=filtered_data)
plt.xlabel('Субъект РФ')
plt.ylabel('Численность студентов заочная форма, человек, 2019')
plt.xticks(rotation=90)
plt.title('Количество студентов (не более 10 000)')
plt.tight_layout()
plt.show()